version: '3'
services:
  front-end:
    build: ./frontend
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./frontend:/app
    networks:
     - livraison-networks
  back-end:
    restart: always
    build:
      context: ./backend 
    volumes:
    - /app/node_modules 
    - ./backend:/app 
    ports:
     - 8080:8080
    networks:
     - livraison-networks     
    env_file: ./backend/.env
    # environment:  
    #   - MONG_URL = "${MONG_URL}"
    depends_on:
     - mongodb
  mongodb:
    image: mongo
    restart: always
    env_file:
      - ./backend/.env  
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${DB_USER_NAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${DB_USER_PASSWORD}
    ports:
     - "27017:27017"
    networks:
     - livraison-networks
    volumes:
     - /data/db 
networks:
  livraison-networks:
    driver: bridge
volumes:
  mongoose-data:
   driver: local
   driver_opts:
      size: "10GiB"
 

       
  